on:
  push:
    branches:
      - integ-tests

name: Integration Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print current build ID
      run: |
        echo Integration test run: githubactionsamazonecsdeplo-NWcjHIgDJLXw:33d5c927-ca82-4ba9-99c9-92cd331adce6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@48ff2ee6526eaef70a7e18de03e01014942d9c65
      with:
        task-definition: task-definition.json
        service: github-actions-deploy-task-def-integ-test
        cluster: github-actions-deploy-task-def-integ-test
        wait-for-service-stability: true
