on:
  push:
    branches:
      - integ-tests

name: Integration Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print current build ID
      run: |
        echo Integration test run: githubactionsamazonecsdeplo-NWcjHIgDJLXw:ecb0a69e-514e-4d6c-b21e-dda87ed159e4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        
    - name: Deploy Amazon ECS task definition with one-off task and wait for task stopped set to false
      uses: aws-actions/amazon-ecs-deploy-task-definition@abe77ebded86b685c231c58bd5936280c6fcc011
      with:
        task-definition: task-definition-run-task.json
        cluster: github-actions-deploy-task-def-integ-test
        run-task: true
        run-task-subnets: subnet-e5604fce, subnet-fe9355b4, subnet-c49431bc, subnet-392f9b64
        run-task-security-groups: sg-067ebcde49c0f3ad8
        run-task-launch-type: FARGATE
        wait-for-task-stopped: false

    - name: Deploy Amazon ECS task definition with one-off task and wait for task stopped set to true
      uses: aws-actions/amazon-ecs-deploy-task-definition@abe77ebded86b685c231c58bd5936280c6fcc011
      with:
        task-definition: github-actions-deploy-task-def-integ-tests
        cluster: github-actions-deploy-task-def-integ-test
        run-task: true
        run-task-subnets: subnet-e5604fce, subnet-fe9355b4, subnet-c49431bc, subnet-392f9b64
        run-task-security-groups: sg-067ebcde49c0f3ad8
        run-task-launch-type: FARGATE
        wait-for-task-stopped: true

    - name: Deploy Amazon ECS task definition with ECS Service
      uses: aws-actions/amazon-ecs-deploy-task-definition@abe77ebded86b685c231c58bd5936280c6fcc011
      with:
        task-definition: task-definition.json
        service: github-actions-deploy-task-def-integ-test
        cluster: github-actions-deploy-task-def-integ-test
        wait-for-service-stability: true